spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon-refactored
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE


server:
  port: 8080