spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon-refactored
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080